### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by XhmikosR**
/CC @micahflee: don't wait like 2 months before you merge this please. :p

### CODE REVIEW

**Comment by XhmikosR** [comment]
@micahflee: also, maybe we should lazy load the images to speed things up?

**Comment by micahflee** [comment]
Thank you! How would lazy loading images work? Like, making them load after everything else rather than just when they load?

**Comment by XhmikosR** [comment]
Can you check out my branch and let me know what you thing?  https://github.com/XhmikosR/fixubuntu/tree/lazyload-images

**Comment by XhmikosR** [comment]
Note, that is a very first patch; it works but I'd like to try https://github.com/vvo/lazyload and also support non JS.

**Comment by XhmikosR** [comment]
@micahflee: the server files are still the old ones.

**Comment by micahflee** [comment]
@XhmikosR I just checked out your lazyload-images branch and it looks great! I merged it into master and deployed it.

**Pull request merged**
