### PR TITLE
Update all dependencies.

### PR DESCRIPTION
**Pull request by XhmikosR**

### CODE REVIEW

**Comment by XhmikosR** [comment]
@micahflee: bump

**Comment by XhmikosR** [comment]
@micahflee: yet another bump

**Comment by XhmikosR** [comment]
Did you touch anything regarding expires date? Is htaccess copied properly?

http://gtmetrix.com/reports/fixubuntu.com/loYr5yVS

**Comment by micahflee** [comment]
Nope I didn't touch anything, and .htaccess appears to be copied correctly. I just compared what's on the server, and it's the exact file that's in the git repo. The performance grade is 100%?

**Comment by XhmikosR** [comment]
@micahflee: the yslow grade is lower; something changed regarding the expires date. Maybe `mod_expires` is again disabled?

**Comment by XhmikosR** [comment]
I definitely see different headers compared to previously. See http://gtmetrix.com/compare/elQzqs9k/kSjyIsJo

**Comment by micahflee** [comment]
Ahh I bet this is related to some apache config changes I recently made. I added a bunch of security-related http headers. It now gets a much better score when testing on https://securityheaders.com/.

Some of the new headers are:

```
Header set Cache-Control "max-age=0, no-cache, no-store, must-revalidate"
Header set Pragma "no-cache"
Header set Expires "-1"
```

This must be what's causing it.

**Comment by XhmikosR** [comment]
Yeah those definitely cause it. We handle all expires dates in htaccess so
those are redundant and produce the opposite of what we want. The rest are
fine to keep.

**Comment by XhmikosR** [comment]
@micahflee: So, can you remove the aforementioned headers?

**Comment by XhmikosR** [comment]
Ping @micahflee

**Comment by micahflee** [comment]
Sorry again! Headers removed.

**Pull request merged**
